#!/bin/sh

### BEGIN INIT INFO
# Provides:          mplayer-web-mouse-remote-control
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: web remote control for mplayer
# Description:       A Python based HTTP server which passes commands to mplayer from a website or mouse clicks
### END INIT INFO

# Configure these:
DIR=/home/pi/mplayer-web-mouse-control
DAEMON_USER=pi
# End of Config

WEB_DAEMON=$DIR/main.py
WEB_DAEMON_NAME=mplayer-web
MOUSE_DAEMON=$DIR/mouse-ctrl.py
MOUSE_DAEMON_NAME=mplayer-mouse
WEB_PIDFILE=$DIR/$WEB_DAEMON_NAME.pid
MOUSE_PIDFILE=$DIR/$MOUSE_DAEMON_NAME.pid

. /lib/lsb/init-functions
 
do_start () {
    log_daemon_msg "Starting system $WEB_DAEMON_NAME daemon"
    start-stop-daemon --start --background --pidfile $WEB_PIDFILE --make-pidfile --user $DAEMON_USER --chuid $DAEMON_USER --startas $WEB_DAEMON
    log_end_msg $?

    log_daemon_msg "Starting system $MOUSE_DAEMON_NAME daemon"
    start-stop-daemon --start --background --pidfile $MOUSE_PIDFILE --make-pidfile --user $DAEMON_USER --chuid $DAEMON_USER --startas $MOUSE_DAEMON
    log_end_msg $?
}
do_stop () {
    log_daemon_msg "Stopping system $WEB_DAEMON_NAME daemon"
    start-stop-daemon --stop --pidfile $WEB_PIDFILE --retry 10
    log_end_msg $?

    log_daemon_msg "Stopping system $MOUSE_DAEMON_NAME daemon"
    start-stop-daemon --stop --pidfile $MOUSE_PIDFILE --retry 10
    log_end_msg $?
}
 
case "$1" in
 
    start|stop)
        do_${1}
        ;;
 
    restart|reload|force-reload)
        do_stop
        do_start
        ;;
 
    status)
        status_of_proc -p $WEB_PIDFILE "$WEB_DAEMON_NAME" "$WEB_DAEMON"
        status_of_proc -p $MOUSE_PIDFILE "$MOUSE_DAEMON_NAME" "$MOUSE_DAEMON"
        ;;
    *)
        echo "Usage: /etc/init.d/mplayer-web-mouse-control {start|stop|restart|status}"
        exit 1
        ;;
 
esac
exit 0
